"""empty message

Revision ID: 492b6df970d2
Revises: 
Create Date: 2024-10-29 15:27:59.076058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492b6df970d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('nacionalidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificado', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('nacionalidade')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
